# Abdomen Scan {#sec-abdo-scan}

## Liver

### Overview

- **Subcostal:** Transverse & longitudinal view of RL & LL (LL must includes **caudate lobe**)

- **Intercostal:** RL

::: {.callout-warning}
#### Beware

Blind spot of liver at “superior portion of Rt lobe” 
:::

![Liver scan plane [@abd-us-step-by-step]](../../img/us/liver-scan-plane.png){#fig-liver-scan-plane width="50%"}


### Measure

- **Normal liver span:** `15 - 17 cm` (sagital, at MCL)

- **Enlarge:** `> 15.5 cm` 

- **Hepatomegaly:** confident if liver extend to caudal of Rt kidney 

(Ref from [@sono-diffuse-liver-dz])

### View: Longitudinal

::: {.panel-tabset}
### Image
::: {layout-nrow=2}
![**Superior border:** longitudinal view [@abd-us-step-by-step]](../../img/us/liver-long-sup.png){#fig-liver-long-sup width="80%"}

![**Inferior border:** longitudinal view [@abd-us-step-by-step]](../../img/us/liver-long-inf.png){#fig-liver-long-inf width="80%"}
:::

### Drawing
::: {layout-nrow=1}
![Superior border: drawing [@abd-us-step-by-step]](../../img/us/liver-long-sup-draw.png){#fig-liver-long-sup-draw width="30%"}

![Inferior border: drawing [@abd-us-step-by-step]](../../img/us/liver-long-inf-draw.png){#fig-liver-long-inf-draw width="35%"}
:::

:::



### View: Transverse


::: {.panel-tabset}
#### Image

::: {layout-nrow=2}
![**Left lobe:** transverse view [@abd-us-step-by-step]](../../img/us/liver-tv-ll.png){#fig-liver-tv-ll width="80%"}

![**Right lobe:** transverse view [@abd-us-step-by-step]](../../img/us/liver-tv-rl.png){#fig-liver-tv-rl width="80%"}
:::

#### Drawing
![Transverse view drawing [@abd-us-step-by-step]](../../img/us/liver-tv-draw.png){#fig-liver-tv-draw width="80%"}

:::

## Billiary

### Gallbladder

- **View:** transverse & longitudinal

- **Measure:** 

    - Diameter: long < 11 cm, TV < 4 cm
    - Wall thickness < 3 mm

## Pancreas

### View

**View: transverse view**, angle the probe slightly upward to the liver.

The *money shot* of the pancrease is shown in [@fig-pancrease-tv-goldenview].

::: {.panel-tabset}
#### Image
![Pancrease: transverse view [@us-anatomy-2004]](../../img/us/pancrease-tv-goldenview.png){#fig-pancrease-tv-goldenview width="80%"}

#### Drawing
![Pancrease: drawing in transverse view [@us-anatomy-2004]](../../img/us/pancrease-tv-goldenview-draw.png){#fig-pancrease-tv-goldenview-draw width="80%"}
:::

### Finding pancreas

::: {.panel-tabset}
#### Landmark
![Pancrease: landmark vessels [@abd-us-step-by-step]](../../img/us/pancrease-tv-landmk.png){#fig-pancrease-tv-landmk width="80%"}

#### Scan
![Pancrease: scanning from rostal to caudal [@abd-us-step-by-step]](../../img/us/pancrease-tv-locating.png){#fig-pancrease-tv-locating width="80%"}
:::


### Tips

Pancrease is best examined in fasted patient. 

If bowel gas obstruct the view, try:

-   Examine after the patient change position:

    -   From **lateral decubitus to supine**, or
    -   From **supine to upright** (sit).

-   Use acoustic windows:

    -   Let the patient **drink some water** to fill in the stomach.

    -   View through the **liver**.