# US Template

## Abdo Normal 

### Normal U/S WA


**FINDINGS:** 

**Liver:** Normal size and parenchymal echogenicity. No focal lesion. 

**Biliary system:** CBD size ___ mm. No intrahepatic ductal dilatation. 

**Gallbladder:** (`[Well | Partially]`)-distended gallbladder. No stone or mass.

**Spleen:** Normal in size. 

**Pancreas:** Visualized portions are unremarkable.

**Kidneys:** Normal size and parenchymal echogenicity of both kidneys. No stone, hydronephrosis or solid mass. 

**Urinary bladder:** No stone or mass. 

**Aorta:** Normal caliber. 

**Peritoneum:** No free fluid. 

(Choose one)

**Prostate gland:** Normal size, measuring ___ ml in volume. 

**Uterus:** Unremarkable.

**Ovaries:** `[Normal size of | Non-visualized]` both ovaries. No gross adnexal mass. 


**IMPRESSION:** [TODO]


### Normal U/S KUB

**FINDING:**

**Right kidney:** Normal size and parenchymal echogenicity, measuring about _ x _ x _ cm. No stone or hydronephrosis. 

**Left kidney:** Normal size and parenchymal echogenicity, measuring about _ x _ x _ cm. No stone or hydronephrosis.

**Bladder:** Well-distended urinary bladder without stone or mass. 

**Uterus:** Endometrial thickness measures about ___ mm. 

**Ovaries and adnexae:** Normal size of both ovaries.

**Others:** No free fluid. 

### Limited study

-   **Bowel gas:** Limited evaluation due to overlying bowel gas.

-   **High liver:** Limited some evaluation due to high liver position.

## HBP Findings 

### History

-  Chronic HBV infection, HCC surveillance.

### Fatty Liver

- **Mild:** Normal size with mildly increased parenchymal echogenicity of the liver,

- **Moderate:** Normal size with (diffusely) increased parenchymal echogenicity of the liver, causing imparied visualization of **intrahepatic vasculature**, 

- **Severe:** Normal size with (diffusely) increased parenchymal echogenicity of the liver, causing imparied visualization of intrahepatic vasculature and **right hemidiaphragm**,


**(Focal fat sparing):** + A geographic hypoechoic lesion at periportal region, suggesting of focal fat sparing. 

... suggesting of `[mild | moderate | severe]` degree fatty liver disease.

+ No focal lesion. 

**IMPRESSION:** 

- `[Mild | Moderate | Severe]` degree fatty liver disease without focal lesion 

### Cirrhosis

- **Liver:** Normal size ? with coarse parenchymal echogenicity and surface nodularity. No focal lesion.  

- **Spleen:** Spleenomegaly ?. No focal lesion.

**IMPRESSION:** 

- Liver cirrhosis without focal lesion.

### Gall Stone

**Gallbladder and biliary system:** A ???-cm gallstone. No gallbladder wall thickening or pericholecystic fluid. Common bile duct size ___ mm. No intrahepatic ductal dilatation. 

**IMPRESSION:** 

- A ???-cm gallstone without evidence of cholecystitis 


### Dilate CBD

**Biliary system:** Dilated CBD measures about ___ mm 


- **(Not seen cause):** + without demonstrable cause of obstruction. No intrahepatic ductal dilatation. 

### Post-cholecystectomy

- **Gallbladder:** Surgically absent gallbladder.

## Renal Findings

### Renal Stone

**Calcified vessel:** Hyperechoic foci at ___, probably calcified vessels or non-obstructive calyceal stone.


**Non-obs, caliceal stone:** Normal size and parenchymal echogenicity of both kidneys. Non-obstructing caliceal stones at ?? pole of ?? kidney, measuring ___. No solid mass.


### Renal Hydronephrosis

**(Distended bladder):** Mildly dilated pelvicalyceal system of right kidney without demonstrable cause of obstruction. 


**IMPRESSION:**

**(Distended bladder):** Mild dilatation of the right pelvocaleceal system, probable reflux from fully-distended urinary bladder.  

### Renal Cyst

A ??-cm cortical cyst...

**(calcify wall):** + with calcified wall.

### CKD

- **Kidneys:** small size with increased parenchymal echogenicity and thinning of cortex. 

### Renal etc.

- **Renal cortical defect**: Focal cortical scar at ___ pole of the ___ kidney. ([ref](https://radiopaedia.org/articles/renal-cortical-defect))

## Repro Findings

### Myoma & Cyst

**Uterus:** 

-   __ of a ? x ? x ?-cm `[intramural | submucosal | subserous]` myoma.

-   Endometrial thickness is measured about __ mm. 

**Ovaries and adnexae:** Normal size of ___ ovaries. A ???-cm cystic lesion at right adnexa, probably functional cyst or endometriotic cyst.


## Thyroid Template

### Normal Thyroid

**US OF THE THYROID** 

**FINDINGS:**

**Thyroid:** 

**Right lobe:** Normal size and homogeneous echogenicity. Size = _ x _ x _ cm. No mass. 

**Left lobe:** Normal size and homogeneous echogencity. Size = _ x _ x _ cm. No mass. 

**Isthmus:** Thickness = ___ mm. 

**Cervical lymph nodes:** No enlargement. 

**IMPRESSION:**

- [TODO]
- No cervical lymphadenopathy


### PTC S/P TTD (1 mo)

**HISTORY:** A ??-year-old woman with papillary thyroid cancer S/P TTD (dd/mm/yyyy) ± with I-131 ablation.

**FINDINGS:** 

-  **Thyroid gland:** Status is post total thyroidectomy. There is a small hypoechoic nodule at `[right | left]` sided of thyroid bed, measuring _ x _ cm., probably residual thyroid tissue or post-operative granulation tissue.

-  **Cervical lymph nodes:** There are multiple subcentrimeter oval-shaped lymph nodes with central fat hilum at the bilateral cervical regions, measuring up to ___ mm in short axis diameter.  

**IMPRESSION:**

- Hypoechoic nodule at `[right | left]` sided of thyroid bed, probably small residual thyroid tissue or post-operative change. Follow-up is advised.
- No cervical lymph node enlargement.  


