project:
  type: book
  execute-dir: project # Use project root as working dir

book:
  title: "Radiology Cookbook"
  author: "Kittipos Sirivongrungson"
  date: today # `today` for current date when render
  site-url: https://radio-cookbook-lightbridge.netlify.app
  repo-url: https://github.com/Lightbridge-KS/radio-cookbook
  repo-actions: edit
  downloads: [docx]
  chapters:
    - index.qmd
    - contents/resources.md
    - contents/style.qmd  
    - part: "Basic"
      chapters: 
      - contents/basic/ct-basic.qmd
    - part: "ER"
      chapters:
      - contents/er/contrast.qmd
      - contents/er/stroke-fast.qmd
      - contents/er/trauma.qmd
    - part: "Neuro"
      chapters:
      - contents/neuro/neuro-anatomy.qmd
      - contents/neuro/mri-neuro.qmd
      - contents/neuro/tmp-ct-brain-loc.qmd
      - contents/neuro/tmp-ct-brain-lesion.qmd
    - part: "Ultrasound"
      chapters:
      - contents/us/us-q-ref.qmd
      - contents/us/us-scan-abdo.qmd
      - contents/us/us-tmp-abdo.qmd
      - contents/us/us-tmp-thyroid.qmd
      - contents/us/us-tmp-scrotum.qmd
    - part: "Abdomen"
      chapters:
      - contents/abdo/ct-abdo.qmd
    - part: "Chest"
      chapters: 
      - contents/chest/chest-tmp-cxr.qmd
    - part: "CVS"
      chapters: 
      - contents/cvs/cvs-temp-doppler.qmd
      
    - bibliography.qmd

bibliography: references.bib
csl: assets/csl/elsevier-with-titles.csl

format:
  html:
    theme: 
      light: cosmo #zephyr
      dark: 
      - slate #cyborg
      - assets/style/theme-dark.scss
  docx:
    toc-depth: 2
    reference-doc: "assets/docx-ref/th-sarabun-new-ref.docx"
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: "assets/pre-tex/thai-preamble.tex" # Thai preamble

css: assets/style/style.css

execute: 
  echo: false

# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto