project:
  type: book
  execute-dir: project # Use project root as working dir

book:
  title: "Radiology Notes"
  author: "Kittipos Sirivongrungson"
  date: today # `today` for current date when render
  site-url: https://radio-notes-lightbridge.netlify.app
  repo-url: https://github.com/Lightbridge-KS/radio-notes
  repo-actions: edit
  chapters:
    - index.qmd
    - contents/style.qmd
    - contents/us-ref.qmd
    - contents/us-temp.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo #zephyr
      dark: solar
  docx: default
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: "assets/pre-tex/thai-preamble.tex" # Thai preamble

execute: 
  echo: false

# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
#freeze: auto