project:
  type: book

book:
  title: "Radiology Notes"
  author: "Kittipos Sirivongrungson"
  date: "4/16/2022" # `today` for current date when render
  #site-url: your-site-url
  repo-url: https://github.com/Lightbridge-KS/radio-notes
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo #zephyr
      dark: solar
  pdf:
    documentclass: scrreprt
    include-in-header: "assets/pre-tex/thai-preamble.tex"


# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
#freeze: auto