project:
  type: book
  execute-dir: project # Use project root as working dir

book:
  title: "Radiology Cookbook"
  author: "Kittipos Sirivongrungson"
  date: today # `today` for current date when render
  site-url: https://radio-notes-lightbridge.netlify.app
  repo-url: https://github.com/Lightbridge-KS/radio-cookbook
  repo-actions: edit
  chapters:
    - index.qmd
    - contents/resources.md
    - contents/style.qmd  
    - part: "Ultrasound"
      chapters:
      - contents/us/us-q-ref.qmd
      - contents/us/us-normal.qmd
      - contents/us/us-tmp-abdo.qmd
      - contents/us/us-tmp-thyroid.qmd
    - bibliography.qmd

bibliography: references.bib
csl: assets/csl/elsevier-with-titles.csl

format:
  html:
    theme: 
      light: cosmo #zephyr
      dark: slate #cyborg
  docx:
    toc-depth: 2
    reference-doc: "assets/docx-ref/th-sarabun-new-ref.docx"
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: "assets/pre-tex/thai-preamble.tex" # Thai preamble

css: assets/style/style.css

execute: 
  echo: false

# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
#freeze: auto