on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:



name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here
      - name: Set up R Environment
        uses: r-lib/actions/setup-renv@v2 # Installs packages from renv lockfile
        with:
          cache-version: 1

      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      
      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          to: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      # - name: Publish to RStudio Connect (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     to: connect
      #     CONNECT_SERVER: enter-the-server-url-here
      #     CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }} 

      # - name: Publish to GitHub Pages (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     to: gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      